on:
  push:
    paths:
      - 'plugins/xx/**'

name: Release

permissions: write-all



jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: zip
        run: zip -r xx.zip plugins/xx/*


      - name: Release-PR
        uses:  google-github-actions/release-please-action@v3.1.2
        with:
          release-type: node
          token: ${{secrets.WORKFLOW}}
          pull-request-title-pattern: "chore${scope}: release ${version}"
          extra-files: plugins/xx/manifest.json




